export const types = {
    // user login
    USER_LOGIN: "USER_LOGIN",
    USER_DETAILS: "USER_DETAILS",
    USER_DELETE: "USER_DELETE",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    USER_BLOCKED: "USER_BLOCKED",
    USER_DISABLED: "USER_DISABLED",
    USER_NEW: "USER_NEW",
    USER_CREATED: "USER_CREATED",

    // user login
    ADMIN_LOGIN: "ADMIN_LOGIN",

    //clear login state
    CLEAR_LOGIN_STATE: "CLEAR_LOGIN_STATE",
}
