export const types = {
    // user login
    USER_LOGIN: "USER_LOGIN",
    USER_DETAILS: "USER_DETAILS",
    USER_DELETE: "USER_DELETE",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    USER_BLOCKED: "USER_BLOCKED",
    USER_DISABLED: "USER_DISABLED",
    USER_NEW: "USER_NEW",
    USER_CREATED: "USER_CREATED",

    // user login
    ADMIN_LOGIN: "ADMIN_LOGIN",

    //clear login state
    CLEAR_LOGIN_STATE: "CLEAR_LOGIN_STATE",

    //SESSION EXPIRY
    SESSION_EXPIRY: "SESSION_EXPIRY",
    SESSION_EXPIRY_SUCCESS: "SESSION_EXPIRY_SUCCESS",
    SESSION_EXPIRY_ERROR: "SESSION_EXPIRY_ERROR",
    CLEAR_SESSION_EXPIRY: "CLEAR_SESSION_EXPIRY",

    //MARKETING UPDATE 
    MARKETING_DETAILS_UPDATE: "MARKETING_DETAILS_UPDATE",
    MARKETING_DETAILS_UPDATE_SUCCESS: "MARKETING_DETAILS_UPDATE_SUCCESS",
    MARKETING_DETAILS_UPDATE_ERROR: "MARKETING_DETAILS_UPDATE_ERROR",

    // get marketing details
    GET_MARKETING_DETAILS: "GET_MARKETING_DETAILS",
    GET_MARKETING_DETAILS_SUCCESS: "GET_MARKETING_DETAILS_SUCCESS",
    GET_MARKETING_DETAILS_ERROR: "GET_MARKETING_DETAILS_ERROR",

    //clear Marketing details
    CLEAR_MARKETING_DETAILS: "CLEAR_MARKETING_DETAILS",
    
    //File Aduit
    FILE_ADUIT:"FILE_ADUIT",
    FILE_ADUIT_SUCCESS:"FILE_ADUIT_SUCCESS",
    FILE_ADUIT_ERROR:"FILE_ADUIT_ERROR",
    CLEAR_FILE_ADUIT: "CLEAR_FILE_ADUIT",

    //System Status
    SYSTEM_STATUS:"SYSTEM_STATUS",
    SYSTEM_STATUS_SUCCESS:"SYSTEM_STATUS_SUCCESS",
    SYSTEM_STATUS_ERROR:"SYSTEM_STATUS_ERROR",

    //Search Result
    SEARCH_RESULT:"SEARCH_RESULT",
    SEARCH_RESULT_SUCCESS:"SEARCH_RESULT_SUCCESS",
    SEARCH_RESULT_ERROR:"SEARCH_RESULT_ERROR",
    CLEAR_SEARCH_RESULT: "CLEAR_SEARCH_RESULT",

    //software Products List details
    SOFTWARE_PRODUCTS: "SOFTWARE_PRODUCTS",
    SOFTWARE_PRODUCTS_SUCCESS: "SOFTWARE_PRODUCTS_SUCCESS",
    SOFTWARE_PRODUCTS_ERROR: "SOFTWARE_PRODUCTS_ERROR",
    CLEAR_SOFTWARE_PRODUCTS: "CLEAR_SOFTWARE_PRODUCTS",

    //GET_LINK
    GET_LINK: "GET_LINK",
    GET_LINK_SUCCESS: "GET_LINK_SUCCESS",
    GET_LINK_ERROR: "GET_LINK_ERROR",
    CLEAR_LINK: "CLEAR_LINK",

    //product Version List details
    PRODUCT_DETAILS: "PRODUCT_DETAILS",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_ERROR: "PRODUCT_DETAILS_ERROR",
    CLEAR_PRODUCT_DETAILS: "CLEAR_PRODUCT_DETAILS",

    //product Version List details
    SUB_PRODUCT: "SUB_PRODUCT",
    SUB_PRODUCT_SUCCESS: "SUB_PRODUCT_SUCCESS",
    SUB_PRODUCT_ERROR: "SUB_PRODUCT_ERROR",
    CLEAR_SUB_PRODUCT: "CLEAR_SUB_PRODUCT",

    //product update
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_ERROR: "UPDATE_PRODUCT_ERROR",

    // new Product
    NEW_PRODUCT: "NEW_PRODUCT",
    NEW_PRODUCT_SUCCESS: "NEW_PRODUCT_SUCCESS",
    NEW_PRODUCT_ERROR: "NEW_PRODUCT_ERROR",
    CLEAR_NEW_PRODUCT_ERROR: "CLEAR_NEW_PRODUCT_ERROR",
    
    // RAISE TICKET
    RAISE_TICKET: "RAISE_TICKET",
    RAISE_TICKET_SUCCESS: "RAISE_TICKET_SUCCESS",
    RAISE_TICKET_ERROR: "RAISE_TICKET_ERROR",
    CLEAR_RAISE_TICKET: "CLEAR_RAISE_TICKET",

    // delete Product
    DELETE_PRODUCT: "DELETE_PRODUCT",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_ERROR: "DELETE_PRODUCT_ERROR",

    //software update
    DELETE_SOFTWARE: "DELETE_SOFTWARE",
    UPDATE_SOFTWARE: "UPDATE_SOFTWARE",
    UPDATE_SOFTWARE_SUCCESS: "UPDATE_SOFTWARE_SUCCESS",
    UPDATE_SOFTWARE_ERROR: "UPDATE_SOFTWARE_ERROR",

    //download software details
    DOWNLOAD_SOFTWARE: "DOWNLOAD_SOFTWARE",
    DOWNLOAD_SOFTWARE_SUCCESS: "DOWNLOAD_SOFTWARE_SUCCESS",
    DOWNLOAD_SOFTWARE_ERROR: "DOWNLOAD_SOFTWARE_ERROR",
    CLEAR_DOWNLOAD_SOFTWARE_DATA: "CLEAR_DOWNLOAD_SOFTWARE_DATA",
    
    //Portal user List details
    PORTAL_USERS: "PORTAL_USERS",
    PORTAL_USERS_SUCCESS: "PORTAL_USERS_SUCCESS",
    PORTAL_USERS_ERROR: "PORTAL_USERS_ERROR",
    CLEAR_PORTAL_USERS: "CLEAR_PORTAL_USERS",

    //Client user List details
    CLIENT_USERS: "CLIENT_USERS",
    CLIENT_USERS_SUCCESS: "CLIENT_USERS_SUCCESS",
    CLIENT_USERS_ERROR: "CLIENT_USERS_ERROR",
    CLEAR_CLIENT_USERS: "CLEAR_CLIENT_USERS",

    //FILE UPLOAD 
    FILE_UPLOAD: "FILE_UPLOAD",
    FILE_UPLOAD_SUCCESS: "FILE_UPLOAD_SUCCESS",
    FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
    CLEAR_FILE_DATA: "CLEAR_FILE_DATA",

    //Product UPLOAD 
    PRODUCT_UPLOAD: "PRODUCT_UPLOAD",
    PRODUCT_UPLOAD_SUCCESS: "PRODUCT_UPLOAD_SUCCESS",
    PRODUCT_UPLOAD_ERROR: "PRODUCT_UPLOAD_ERROR",
    CLEAR_NEW_PRODUCT_DATA: "CLEAR_NEW_PRODUCT_DATA",
    UPDATE_PRODUCT_UPLOAD: "UPDATE_PRODUCT_UPLOAD",
    
    //Home page Products List
    HOME_PAGE_PRODUCTS: "HOME_PAGE_PRODUCTS",
    HOME_PAGE_PRODUCTS_SUCCESS: "HOME_PAGE_PRODUCTS_SUCCESS",
    HOME_PAGE_PRODUCTS_ERROR: "HOME_PAGE_PRODUCTS_ERROR",
    CLEAR_HOME_PAGE_PRODUCTS: "CLEAR_HOME_PAGE_PRODUCTS",

    //Users Update details
    UPDATE_USERS: "UPDATE_USERS",
    UPDATE_USERS_SUCCESS: "UPDATE_USERS_SUCCESS",
    UPDATE_USERS_ERROR: "UPDATE_USERS_ERROR",
    CLEAR_UPDATE_USERS: "CLEAR_UPDATE_USERS",
}
